ALTER TABLE Users ADD CONSTRAINT DF_Users DEFAULT GETDATE() FOR LastLoginTime

ALTER TABLE Users
DROP CONSTRAINT CHK_PassordLength

ALTER TABLE Users
ADD CONSTRAINT CHK_PassordLength CHECK (LEN(Password) > 4)

